title: "ASISTENTE"
description: "Descripci贸n de tu proyecto ASISTENTE"
baseurl: "" # La URL base del sitio, por ejemplo, /blog
url: "https://fabyelias.github.io/ASISTENTE" # La URL completa del sitio

# Configuraci贸n de GitHub Pages
theme: jekyll-theme-primer

# Configuraci贸n de Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata

# Paginaci贸n
paginate: 5
paginate_path: "/page:num/"